markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
highlighter: pygments
paginate: 100
permalink: /:title

title: 即刻出发
url: http://wy-ei.com
feed: /atom.xml
author_info: <a href="http://wy-ei.com">即刻出发</a>

author :
  name : 即刻出发
  email : nameiswangyu@163.com
  github : wy-ei
JB:
  tags_path : /tags.html

  comments :
    provider : disqus
    disqus :
      short_name : wy-ei
