markdown: kramdown
kramdown: 
  input: GFM
highlighter: rouge
paginate: 100
permalink: /:title

title: 即刻出发
url: http://wy-ei.com
rss_path: /rss.xml
atom_path: /atom.xml
author_info: <a href="http://wy-ei.com">即刻出发</a>
excerpt_separator: "<!--more-->"
author :
  name : wy-ei
  email : nameiswangyu@163.com
  github : wy-ei
